import React, { createContext, useContext, useState, useCallback, useMemo } from 'react';

const translations = {
  en: {
    // Navigation
    nav: {
      about: 'About',
      strategies: 'Strategies',
      governance: 'Governance & Risks',
      europeanApproach: 'European Approach',
      investors: 'Investors',
      contact: 'Contact',
    },
    // Hero
    hero: {
      headline: 'Building Resilient Value Across Cycles',
      subheadline: 'Alternative Investment Strategies with Institutional Discipline',
      cta: 'Our Strategies',
      ctaSecondary: 'Contact Us',
    },
    // Home sections
    home: {
      whoWeAre: 'Who We Are',
      whoWeAreText: 'FINXIA CAPITAL is an independent pan-European alternative asset manager focused on creating long-term value through disciplined investment strategies and sophisticated structuring.',
      approachTitle: 'Our Investment Approach',
      approachText: 'We combine institutional rigor with entrepreneurial agility, focusing on opportunities where our expertise in real estate and capital markets creates sustainable value.',
      pillarsTitle: 'Strategic Pillars',
      pillar1Title: 'Institutional Discipline',
      pillar1Text: 'Rigorous investment process with strict governance and risk management frameworks.',
      pillar2Title: 'Pan-European Focus',
      pillar2Text: 'Strategic positioning across key European markets with local expertise.',
      pillar3Title: 'Hybrid Architecture',
      pillar3Text: 'Combining value creation with recurring income through diversified strategies.',
      pillar4Title: 'Advanced Structuring',
      pillar4Text: 'Sophisticated fund architecture with institutional-grade governance.',
      governanceTitle: 'Institutional Framework',
      governanceText: 'Our investment decisions are guided by a rigorous governance framework, ensuring alignment with investor interests and long-term value creation.',
      learnMore: 'Learn More',
    },
    // About
    about: {
      title: 'About FINXIA CAPITAL',
      subtitle: 'Independent Asset Management with European Excellence',
      whoTitle: 'Who We Are',
      whoText1: 'FINXIA CAPITAL is an independent asset management company with a pan-European focus, dedicated to delivering superior risk-adjusted returns through disciplined investment strategies.',
      whoText2: 'Our team combines deep expertise in real estate, capital markets, and institutional fund management to identify and execute compelling investment opportunities across Europe.',
      philosophyTitle: 'Our Philosophy',
      philosophyText: 'We believe in a rigorous approach to investing, combining prudent structuring with a long-term vision. Our methodology emphasizes capital preservation while pursuing attractive returns.',
      architectureTitle: 'Fund Architecture',
      architectureText: 'Our fund is structured as a Luxembourg SCSp with ring-fenced compartments, ensuring strict separation of risks and alignment with institutional standards.',
      structure1: 'Luxembourg SCSp Structure',
      structure2: 'Ring-fencing by Strategy',
      structure3: 'Strict Risk Separation',
      structure4: 'AIFMD Compliant Framework',
      governanceTitle: 'Governance',
      governanceText: 'Our governance framework ensures the highest standards of institutional oversight and investor protection.',
      gov1Title: 'Investment Committee',
      gov1Text: 'Rigorous review of all investment decisions',
      gov2Title: 'Validation Process',
      gov2Text: 'Multi-stage approval framework',
      gov3Title: 'Monitoring Cadence',
      gov3Text: 'Regular portfolio reviews and reporting',
      gov4Title: 'Risk Management',
      gov4Text: 'Continuous risk assessment and mitigation',
      // Team section
      teamTitle: 'Founding Team',
      teamSubtitle: 'Experienced Leadership with Proven Track Records',
      founder1Name: 'Jean-Pierre Véron',
      founder1Role: 'Founder & Chairman',
      founder1Bio: 'Seasoned real estate investment professional with over 25 years of experience. FINXIA CAPITAL represents his third institutional fund dedicated to European real estate. Former CEO of K&B, a leading pan-European real estate investment platform. Recognized for his disciplined approach to value creation and institutional governance.',
      founder1Highlight1: 'Third institutional real estate fund',
      founder1Highlight2: 'Former CEO of K&B',
      founder1Highlight3: '25+ years in real estate investment',
      founder2Name: 'Lila Benhammou',
      founder2Role: 'Co-Founder & Chief Investment Officer',
      founder2Bio: 'Serial entrepreneur with deep expertise in emerging technologies, artificial intelligence, and quantitative finance. Combines a strong financial background with forward-thinking investment strategies. Brings innovative approaches to asset management and portfolio optimization.',
      founder2Highlight1: 'Serial entrepreneur in Tech & AI',
      founder2Highlight2: 'Strong quantitative finance background',
      founder2Highlight3: 'Innovation-driven investment approach',
      // Vision & Trajectory
      visionLabel: 'Our Vision',
      visionTitle: 'Shaping the Future of European Alternative Investments',
      visionText: 'FINXIA CAPITAL aims to become a reference pan-European alternative asset manager, recognized for its institutional discipline, innovation capacity, and ability to generate sustainable value across market cycles.',
      visionText2: 'We build lasting partnerships with institutional investors by combining traditional real estate expertise with emerging technologies and innovative capital strategies.',
      trajectoryLabel: 'Our Trajectory',
      trajectoryTitle: 'Strategic Roadmap 2025-2029',
      trajectory1: 'Foundation & Deployment',
      trajectory1Text: 'Initial fund structuring, strategic partnerships, first investments in datacenter infrastructure and hospitality.',
      trajectory2: 'Optimization & Growth',
      trajectory2Text: 'Portfolio optimization, value creation through active management, geographic expansion.',
      trajectory3: 'Value Realization',
      trajectory3Text: 'Strategic exits, return distribution to investors, preparation for Fund II launch.',
      // Differentiating Factors
      diffTitle: 'What Sets Us Apart',
      diffSubtitle: 'A unique combination of institutional rigor, technological innovation, and entrepreneurial agility that distinguishes FINXIA CAPITAL in the European alternative investment landscape.',
      diff1Title: 'Hybrid Architecture',
      diff1Text: 'Unique multi-pocket structure combining real estate (logistics, hospitality, residential) with late-stage capital opportunities for enhanced returns.',
      diff2Title: 'Tech-Driven Edge',
      diff2Text: 'AI and data science integration for deal sourcing, portfolio optimization, and risk monitoring. Bringing PropTech innovation to institutional asset management.',
      diff3Title: 'Snowball Strategy',
      diff3Text: 'Proprietary capital recycling mechanism that amplifies returns through strategic reinvestment, creating a compounding effect across investment cycles.',
      diff4Title: 'Aligned Interests',
      diff4Text: 'Significant GP commitment with performance-based compensation. Our success is directly tied to investor outcomes.',
      // Investment Team
      investmentTeamTitle: 'Investment Team',
      team1Name: 'Marc Dubois',
      team1Role: 'Head of Real Estate',
      team2Name: 'Sophie Chen',
      team2Role: 'Director, Acquisitions',
      team3Name: 'Philippe Laurent',
      team3Role: 'Head of Asset Management',
      team4Name: 'Anna Rossi',
      team4Role: 'Director, Investor Relations',
    },
    // Strategies
    strategies: {
      title: 'Investment Strategies',
      subtitle: 'Diversified Approaches for Sustainable Value Creation',
      strategy1Title: 'Logistics Core & Value-Add',
      strategy1Text: 'Pan-European logistics platforms with focus on Grade A assets, operational optimization, and active asset management across key logistics corridors.',
      strategy1Focus: 'Focus: France, Spain, Italy',
      strategy2Title: 'Hospitality Premium',
      strategy2Text: 'Hybrid approach combining long-term holding with selective rotation of premium urban hotel assets in prime European locations.',
      strategy2Focus: 'Focus: Prime Urban Locations',
      strategy3Title: 'Residential / Flexible Living',
      strategy3Text: 'Operated urban strategies targeting the flexible living segment with focus on occupancy rate optimization and platform approach.',
      strategy3Focus: 'Focus: Major European Cities',
      strategy4Title: 'Capital Opportunités',
      strategy4Text: 'Late-stage investments, secondaries, and special situations with a disciplined and highly selective approach to capital deployment.',
      strategy4Focus: 'Focus: Strategic Opportunities',
      philosophyLabel: 'Philosophy',
      methodologyLabel: 'Methodology',
      riskLabel: 'Risk Discipline',
      horizonLabel: 'Horizon',
      methodologyText: 'Active management with institutional oversight',
      riskText: 'Conservative leverage, strict covenants',
      horizonText: 'Medium to long-term value creation',
    },
    // Risk Management
    risk: {
      title: 'Risk Management',
      subtitle: 'Institutional Standards for Capital Protection',
      intro: 'Our risk management framework ensures rigorous oversight and protection of investor capital through disciplined processes and institutional governance.',
      item1Title: 'Concentration Limits',
      item1Text: 'Strict limits on single-asset and geographic concentration to ensure portfolio diversification.',
      item2Title: 'LTV Discipline',
      item2Text: 'Conservative loan-to-value ratios across all strategies with clearly defined limits.',
      item3Title: 'DSCR Framework',
      item3Text: 'Debt service coverage ratio monitoring to ensure sustainable debt levels.',
      item4Title: 'Systematic Stress Tests',
      item4Text: 'Regular scenario analysis to assess portfolio resilience under adverse conditions.',
      item5Title: 'Quarterly Review Process',
      item5Text: 'Comprehensive quarterly reviews of all investments and risk exposures.',
      item6Title: 'Ring-fencing by Compartment',
      item6Text: 'Legal separation of strategies to isolate risks within each investment pocket.',
      item7Title: 'Institutional Governance',
      item7Text: 'Independent oversight with institutional-grade governance structures.',
      commitment: 'Our Commitment',
      commitmentText: 'Capital protection and risk management are at the core of everything we do. Our institutional framework ensures that investor interests are always protected.',
    },
    // European Approach
    europe: {
      title: 'European Approach',
      subtitle: 'Focused Investment in Key Southern European Markets',
      intro: 'FINXIA CAPITAL focuses on three strategic European markets where we combine deep local expertise with institutional discipline to create lasting value.',
      france: 'France',
      franceText: 'Our core market with strong positions in datacenter infrastructure, premium hospitality, and urban residential. Deep network and proven track record across major French metropolitan areas.',
      spain: 'Spain',
      spainText: 'Dynamic market with attractive risk-adjusted opportunities in logistics and hospitality sectors. Focus on prime locations in major cities and tourist destinations.',
      italy: 'Italy',
      italyText: 'Selective investments in premium urban hospitality and residential assets. Targeting Milan, Rome, and Florence with disciplined value-add approach.',
      diversificationTitle: 'Diversification Strategy',
      diversificationText: 'Our focused European approach provides natural diversification while maintaining concentration on markets where we have competitive advantages, local expertise, and established partnerships.',
      marketsLabel: 'Our Markets',
      marketsTitle: 'Investment Zones',
      keyCities: 'Key Cities',
      strategyFocus: 'Strategies',
      statCountries: 'Target Countries',
      statCities: 'European Metropolises',
      statStrategies: 'Real Estate Strategies',
      criteriaLabel: 'Selection Criteria',
      criteriaTitle: 'Our Market Selection Approach',
      criteriaText: 'We select our markets based on strict criteria of liquidity, market depth, and value creation potential.',
      criteria1: 'Liquid markets with institutional depth',
      criteria2: 'Positive demographic and economic dynamics',
      criteria3: 'Stable and transparent regulatory framework',
      criteria4: 'Access to quality local partners',
    },
    // Investors
    investors: {
      title: 'Investor Relations',
      subtitle: 'Long-term Partnerships Built on Trust and Transparency',
      intro: 'FINXIA CAPITAL is committed to building lasting partnerships with institutional investors through transparent communication and aligned interests.',
      partnershipTitle: 'Long-term Partnerships',
      partnershipText: 'We prioritize building enduring relationships with our investors, based on mutual trust and shared investment objectives.',
      alignmentTitle: 'Alignment of Interests',
      alignmentText: 'Our fee structure and investment approach ensure strong alignment between the interests of our team and our investors.',
      transparencyTitle: 'Transparency',
      transparencyText: 'Regular and comprehensive reporting provides investors with full visibility into portfolio performance and risk exposures.',
      reportingTitle: 'Structured Reporting',
      reportingText: 'Institutional-grade reporting in compliance with international standards and best practices.',
      ilpaTitle: 'ILPA Compliant',
      ilpaText: 'Our reporting and governance frameworks adhere to ILPA (Institutional Limited Partners Association) guidelines.',
      cta: 'Investor Relations',
      ctaText: 'For institutional investor inquiries, please contact our investor relations team.',
    },
    // Contact
    contact: {
      title: 'Contact',
      subtitle: 'We Welcome Your Inquiries',
      formTitle: 'Get in Touch',
      nameLabel: 'Full Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email Address',
      emailPlaceholder: 'your@email.com',
      companyLabel: 'Company / Institution',
      companyPlaceholder: 'Your company (optional)',
      investorTypeLabel: 'Investor Type',
      investorTypePlaceholder: 'Select investor type',
      messageLabel: 'Message',
      messagePlaceholder: 'How can we assist you?',
      submitButton: 'Send Message',
      submitting: 'Sending...',
      successTitle: 'Message Sent',
      successText: 'Thank you for your inquiry. We will respond within 48 hours.',
      errorText: 'An error occurred. Please try again or email us directly.',
      institutionalInvestor: 'Institutional Investor',
      familyOffice: 'Family Office',
      privateInvestor: 'Professional Private Investor',
      advisor: 'Financial Advisor',
      other: 'Other',
      addressTitle: 'Office',
      addressLine1: 'Luxembourg',
      addressLine2: 'Grand Duchy of Luxembourg',
      emailTitle: 'Email',
      email: 'contact@finxiacapital.com',
    },
    // Footer
    footer: {
      description: 'Independent pan-European alternative asset manager focused on hybrid multi-asset strategies.',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms of Use',
      disclaimer: 'Regulatory Disclaimer',
      cookies: 'Cookie Policy',
      copyright: '© 2025 FINXIA CAPITAL. All rights reserved.',
      disclaimerText: 'This website is for informational purposes only and does not constitute an offer to sell or a solicitation of an offer to buy any securities. Investment involves risk.',
    },
  },
  fr: {
    // Navigation
    nav: {
      about: 'À Propos',
      strategies: 'Stratégies',
      governance: 'Gouvernance & Risques',
      europeanApproach: 'Approche Européenne',
      investors: 'Investisseurs',
      contact: 'Contact',
    },
    // Hero
    hero: {
      headline: 'Construire une Valeur Résiliente à Travers les Cycles',
      subheadline: 'Stratégies d\'Investissement Alternatives avec Discipline Institutionnelle',
      cta: 'Nos Stratégies',
      ctaSecondary: 'Nous Contacter',
    },
    // Home sections
    home: {
      whoWeAre: 'Qui Nous Sommes',
      whoWeAreText: 'FINXIA CAPITAL est un gestionnaire d\'actifs alternatifs indépendant pan-européen, focalisé sur la création de valeur à long terme à travers des stratégies d\'investissement disciplinées et une structuration sophistiquée.',
      approachTitle: 'Notre Approche d\'Investissement',
      approachText: 'Nous combinons la rigueur institutionnelle avec l\'agilité entrepreneuriale, en nous concentrant sur les opportunités où notre expertise en immobilier et marchés de capitaux crée une valeur durable.',
      pillarsTitle: 'Piliers Stratégiques',
      pillar1Title: 'Discipline Institutionnelle',
      pillar1Text: 'Processus d\'investissement rigoureux avec gouvernance stricte et cadres de gestion des risques.',
      pillar2Title: 'Focus Pan-Européen',
      pillar2Text: 'Positionnement stratégique sur les marchés européens clés avec expertise locale.',
      pillar3Title: 'Architecture Hybride',
      pillar3Text: 'Combinaison de création de valeur et de revenus récurrents à travers des stratégies diversifiées.',
      pillar4Title: 'Structuration Avancée',
      pillar4Text: 'Architecture de fonds sophistiquée avec gouvernance de qualité institutionnelle.',
      governanceTitle: 'Cadre Institutionnel',
      governanceText: 'Nos décisions d\'investissement sont guidées par un cadre de gouvernance rigoureux, assurant l\'alignement avec les intérêts des investisseurs et la création de valeur à long terme.',
      learnMore: 'En Savoir Plus',
    },
    // About
    about: {
      title: 'À Propos de FINXIA CAPITAL',
      subtitle: 'Gestion d\'Actifs Indépendante avec Excellence Européenne',
      whoTitle: 'Qui Nous Sommes',
      whoText1: 'FINXIA CAPITAL est une société de gestion d\'actifs indépendante avec un focus pan-européen, dédiée à délivrer des rendements ajustés au risque supérieurs à travers des stratégies d\'investissement disciplinées.',
      whoText2: 'Notre équipe combine une expertise approfondie en immobilier, marchés de capitaux et gestion de fonds institutionnels pour identifier et exécuter des opportunités d\'investissement attractives à travers l\'Europe.',
      philosophyTitle: 'Notre Philosophie',
      philosophyText: 'Nous croyons en une approche rigoureuse de l\'investissement, combinant une structuration prudente avec une vision à long terme. Notre méthodologie met l\'accent sur la préservation du capital tout en poursuivant des rendements attractifs.',
      architectureTitle: 'Architecture du Fonds',
      architectureText: 'Notre fonds est structuré comme une SCSp luxembourgeoise avec des compartiments cloisonnés, assurant une séparation stricte des risques et un alignement avec les standards institutionnels.',
      structure1: 'Structure SCSp Luxembourg',
      structure2: 'Cloisonnement par Stratégie',
      structure3: 'Séparation Stricte des Risques',
      structure4: 'Cadre Conforme AIFMD',
      governanceTitle: 'Gouvernance',
      governanceText: 'Notre cadre de gouvernance assure les plus hauts standards de supervision institutionnelle et de protection des investisseurs.',
      gov1Title: 'Comité d\'Investissement',
      gov1Text: 'Examen rigoureux de toutes les décisions d\'investissement',
      gov2Title: 'Processus de Validation',
      gov2Text: 'Cadre d\'approbation multi-étapes',
      gov3Title: 'Cadence de Suivi',
      gov3Text: 'Revues régulières du portefeuille et reporting',
      gov4Title: 'Gestion des Risques',
      gov4Text: 'Évaluation continue des risques et atténuation',
      // Team section
      teamTitle: 'Équipe Fondatrice',
      teamSubtitle: 'Un Leadership Expérimenté aux Parcours Éprouvés',
      founder1Name: 'Jean-Pierre Véron',
      founder1Role: 'Fondateur & Président',
      founder1Bio: 'Professionnel chevronné de l\'investissement immobilier avec plus de 25 ans d\'expérience. FINXIA CAPITAL représente son troisième fonds institutionnel dédié à l\'immobilier européen. Ancien PDG de K&B, plateforme d\'investissement immobilier pan-européenne de premier plan. Reconnu pour son approche disciplinée de la création de valeur et de la gouvernance institutionnelle.',
      founder1Highlight1: 'Troisième fonds immobilier institutionnel',
      founder1Highlight2: 'Ancien PDG de K&B',
      founder1Highlight3: '25+ ans dans l\'investissement immobilier',
      founder2Name: 'Lila Benhammou',
      founder2Role: 'Co-Fondatrice & Directrice des Investissements (CIO)',
      founder2Bio: 'Serial entrepreneur avec une expertise approfondie dans les technologies émergentes, l\'intelligence artificielle et la finance quantitative. Combine un solide parcours financier avec des stratégies d\'investissement innovantes. Apporte des approches novatrices à la gestion d\'actifs et à l\'optimisation de portefeuille.',
      founder2Highlight1: 'Serial entrepreneur en Tech & IA',
      founder2Highlight2: 'Solide parcours en finance quantitative',
      founder2Highlight3: 'Approche d\'investissement axée sur l\'innovation',
      // Vision & Trajectory
      visionLabel: 'Notre Vision',
      visionTitle: 'Façonner l\'Avenir de l\'Investissement Alternatif Européen',
      visionText: 'FINXIA CAPITAL ambitionne de devenir un gestionnaire d\'actifs alternatifs pan-européen de référence, reconnu pour sa discipline institutionnelle, sa capacité d\'innovation et son aptitude à générer une valeur durable à travers les cycles de marché.',
      visionText2: 'Nous construisons des partenariats durables avec les investisseurs institutionnels en combinant l\'expertise immobilière traditionnelle avec les technologies émergentes et les stratégies de capital innovantes.',
      trajectoryLabel: 'Notre Trajectoire',
      trajectoryTitle: 'Feuille de Route Stratégique 2025-2029',
      trajectory1: 'Fondation & Déploiement',
      trajectory1Text: 'Structuration initiale du fonds, partenariats stratégiques, premiers investissements en infrastructure datacenter et hôtellerie.',
      trajectory2: 'Optimisation & Croissance',
      trajectory2Text: 'Optimisation du portefeuille, création de valeur par gestion active, expansion géographique.',
      trajectory3: 'Réalisation de Valeur',
      trajectory3Text: 'Sorties stratégiques, distribution des rendements aux investisseurs, préparation du lancement du Fonds II.',
      // Differentiating Factors
      diffTitle: 'Ce Qui Nous Distingue',
      diffSubtitle: 'Une combinaison unique de rigueur institutionnelle, d\'innovation technologique et d\'agilité entrepreneuriale qui distingue FINXIA CAPITAL dans le paysage de l\'investissement alternatif européen.',
      diff1Title: 'Architecture Hybride',
      diff1Text: 'Structure multi-poches unique combinant immobilier (logistique, hôtellerie, résidentiel) avec des opportunités de capital late-stage pour des rendements amplifiés.',
      diff2Title: 'Avantage Technologique',
      diff2Text: 'Intégration IA et data science pour le sourcing, l\'optimisation de portefeuille et le suivi des risques. Innovation PropTech au service de la gestion institutionnelle.',
      diff3Title: 'Stratégie Snowball',
      diff3Text: 'Mécanisme propriétaire de recyclage du capital qui amplifie les rendements par réinvestissement stratégique, créant un effet de composition à travers les cycles.',
      diff4Title: 'Alignement des Intérêts',
      diff4Text: 'Engagement significatif du GP avec rémunération liée à la performance. Notre succès est directement lié aux résultats des investisseurs.',
      // Investment Team
      investmentTeamTitle: 'Équipe d\'Investissement',
      team1Name: 'Marc Dubois',
      team1Role: 'Directeur Immobilier',
      team2Name: 'Sophie Chen',
      team2Role: 'Directrice Acquisitions',
      team3Name: 'Philippe Laurent',
      team3Role: 'Directeur Asset Management',
      team4Name: 'Anna Rossi',
      team4Role: 'Directrice Relations Investisseurs',
    },
    // Strategies
    strategies: {
      title: 'Stratégies d\'Investissement',
      subtitle: 'Approches Diversifiées pour une Création de Valeur Durable',
      strategy1Title: 'Datacenter AI Brown-to-Green',
      strategy1Text: 'Transformation de datacenters sous-performants en infrastructure IA de nouvelle génération : décarbonée, certifiée, dimensionnée pour les workloads d\'intelligence artificielle.',
      strategy1Focus: 'Focus : France, Espagne, Italie',
      strategy2Title: 'Hôtellerie Premium',
      strategy2Text: 'Approche hybride combinant détention long terme et rotation sélective d\'actifs hôteliers premium dans des emplacements urbains prime en Europe.',
      strategy2Focus: 'Focus : Emplacements Urbains Prime',
      strategy3Title: 'Résidentiel / Flexible Living',
      strategy3Text: 'Stratégies urbaines opérées ciblant le segment flexible living avec focus sur l\'optimisation des taux d\'occupation et approche plateforme.',
      strategy3Focus: 'Focus : Grandes Métropoles Européennes',
      strategy4Title: 'Capital Opportunités',
      strategy4Text: 'Investissements late-stage, secondaires et situations spéciales avec une approche disciplinée et hautement sélective du déploiement de capital.',
      strategy4Focus: 'Focus : Opportunités Stratégiques',
      philosophyLabel: 'Philosophie',
      methodologyLabel: 'Méthodologie',
      riskLabel: 'Discipline de Risque',
      horizonLabel: 'Horizon',
      methodologyText: 'Gestion active avec supervision institutionnelle',
      riskText: 'Levier conservateur, covenants stricts',
      horizonText: 'Création de valeur moyen à long terme',
    },
    // Risk Management
    risk: {
      title: 'Gestion des Risques',
      subtitle: 'Standards Institutionnels pour la Protection du Capital',
      intro: 'Notre cadre de gestion des risques assure une supervision rigoureuse et une protection du capital des investisseurs à travers des processus disciplinés et une gouvernance institutionnelle.',
      item1Title: 'Limites de Concentration',
      item1Text: 'Limites strictes sur la concentration par actif et géographique pour assurer la diversification du portefeuille.',
      item2Title: 'Discipline LTV',
      item2Text: 'Ratios loan-to-value conservateurs sur toutes les stratégies avec des limites clairement définies.',
      item3Title: 'Cadre DSCR',
      item3Text: 'Suivi du ratio de couverture du service de la dette pour assurer des niveaux d\'endettement durables.',
      item4Title: 'Stress Tests Systématiques',
      item4Text: 'Analyse de scénarios régulière pour évaluer la résilience du portefeuille dans des conditions adverses.',
      item5Title: 'Processus de Revue Trimestriel',
      item5Text: 'Revues trimestrielles complètes de tous les investissements et expositions aux risques.',
      item6Title: 'Cloisonnement par Compartiment',
      item6Text: 'Séparation juridique des stratégies pour isoler les risques au sein de chaque poche d\'investissement.',
      item7Title: 'Gouvernance Institutionnelle',
      item7Text: 'Supervision indépendante avec structures de gouvernance de qualité institutionnelle.',
      commitment: 'Notre Engagement',
      commitmentText: 'La protection du capital et la gestion des risques sont au cœur de tout ce que nous faisons. Notre cadre institutionnel assure que les intérêts des investisseurs sont toujours protégés.',
    },
    // European Approach
    europe: {
      title: 'Approche Européenne',
      subtitle: 'Investissement Ciblé sur les Marchés Clés d\'Europe du Sud',
      intro: 'FINXIA CAPITAL se concentre sur trois marchés européens stratégiques où nous combinons une expertise locale approfondie avec une discipline institutionnelle pour créer une valeur durable.',
      france: 'France',
      franceText: 'Notre marché cœur avec des positions fortes en logistique, hôtellerie premium et résidentiel urbain. Réseau étendu et track record éprouvé sur les grandes métropoles françaises.',
      spain: 'Espagne',
      spainText: 'Marché dynamique avec des opportunités attractives ajustées au risque dans les secteurs datacenter et hôtelier. Focus sur les emplacements prime des grandes villes et destinations touristiques.',
      italy: 'Italie',
      italyText: 'Investissements sélectifs dans l\'hôtellerie urbaine premium et le résidentiel. Ciblage de Milan, Rome et Florence avec une approche value-add disciplinée.',
      diversificationTitle: 'Stratégie de Diversification',
      diversificationText: 'Notre approche européenne focalisée offre une diversification naturelle tout en maintenant la concentration sur les marchés où nous avons des avantages compétitifs, une expertise locale et des partenariats établis.',
      marketsLabel: 'Nos Marchés',
      marketsTitle: 'Zones d\'Investissement',
      keyCities: 'Villes Clés',
      strategyFocus: 'Stratégies',
      statCountries: 'Pays Cibles',
      statCities: 'Métropoles Européennes',
      statStrategies: 'Stratégies Immobilières',
      criteriaLabel: 'Critères de Sélection',
      criteriaTitle: 'Notre Approche de Sélection',
      criteriaText: 'Nous sélectionnons nos marchés selon des critères stricts de liquidité, de profondeur de marché et de potentiel de création de valeur.',
      criteria1: 'Marchés liquides avec profondeur institutionnelle',
      criteria2: 'Dynamique démographique et économique positive',
      criteria3: 'Cadre réglementaire stable et transparent',
      criteria4: 'Accès à des partenaires locaux de qualité',
    },
    // Investors
    investors: {
      title: 'Relations Investisseurs',
      subtitle: 'Partenariats Long Terme Construits sur la Confiance et la Transparence',
      intro: 'FINXIA CAPITAL s\'engage à construire des partenariats durables avec les investisseurs institutionnels à travers une communication transparente et des intérêts alignés.',
      partnershipTitle: 'Partenariats Long Terme',
      partnershipText: 'Nous priorisons la construction de relations durables avec nos investisseurs, basées sur la confiance mutuelle et des objectifs d\'investissement partagés.',
      alignmentTitle: 'Alignement des Intérêts',
      alignmentText: 'Notre structure de frais et approche d\'investissement assurent un fort alignement entre les intérêts de notre équipe et de nos investisseurs.',
      transparencyTitle: 'Transparence',
      transparencyText: 'Un reporting régulier et complet fournit aux investisseurs une visibilité complète sur la performance du portefeuille et les expositions aux risques.',
      reportingTitle: 'Reporting Structuré',
      reportingText: 'Reporting de qualité institutionnelle conforme aux standards internationaux et meilleures pratiques.',
      ilpaTitle: 'Conforme ILPA',
      ilpaText: 'Nos cadres de reporting et gouvernance adhèrent aux directives ILPA (Institutional Limited Partners Association).',
      cta: 'Relations Investisseurs',
      ctaText: 'Pour les demandes d\'investisseurs institutionnels, veuillez contacter notre équipe relations investisseurs.',
    },
    // Contact
    contact: {
      title: 'Contact',
      subtitle: 'Nous Accueillons Vos Demandes',
      formTitle: 'Nous Contacter',
      nameLabel: 'Nom Complet',
      namePlaceholder: 'Votre nom',
      emailLabel: 'Adresse Email',
      emailPlaceholder: 'votre@email.com',
      companyLabel: 'Société / Institution',
      companyPlaceholder: 'Votre société (optionnel)',
      investorTypeLabel: 'Type d\'Investisseur',
      investorTypePlaceholder: 'Sélectionner le type',
      messageLabel: 'Message',
      messagePlaceholder: 'Comment pouvons-nous vous aider ?',
      submitButton: 'Envoyer le Message',
      submitting: 'Envoi en cours...',
      successTitle: 'Message Envoyé',
      successText: 'Merci pour votre demande. Nous vous répondrons sous 48 heures.',
      errorText: 'Une erreur s\'est produite. Veuillez réessayer ou nous contacter directement par email.',
      institutionalInvestor: 'Investisseur Institutionnel',
      familyOffice: 'Family Office',
      privateInvestor: 'Investisseur Privé Professionnel',
      advisor: 'Conseiller Financier',
      other: 'Autre',
      addressTitle: 'Bureau',
      addressLine1: 'Luxembourg',
      addressLine2: 'Grand-Duché de Luxembourg',
      emailTitle: 'Email',
      email: 'contact@finxiacapital.com',
    },
    // Footer
    footer: {
      description: 'Gestionnaire d\'actifs alternatifs indépendant pan-européen focalisé sur les stratégies multi-actifs hybrides.',
      quickLinks: 'Liens Rapides',
      legal: 'Légal',
      privacy: 'Politique de Confidentialité',
      terms: 'Conditions d\'Utilisation',
      disclaimer: 'Avertissement Réglementaire',
      cookies: 'Politique des Cookies',
      copyright: '© 2025 FINXIA CAPITAL. Tous droits réservés.',
      disclaimerText: 'Ce site web est à des fins informatives uniquement et ne constitue pas une offre de vente ou une sollicitation d\'offre d\'achat de titres. L\'investissement comporte des risques.',
    },
  },
};

// TypeScript type for the context
type LanguageContextType = {
  language: 'en' | 'fr';
  setLanguage: (lang: 'en' | 'fr') => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'fr'>('fr');

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => (prev === 'fr' ? 'en' : 'fr'));
    // Using functional setState, no need for setLanguage or prev in deps
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const t = useCallback(
    (key: string) => {
      const keys = key.split('.');
      let value: any = translations[language];
      for (const k of keys) {
        value = value?.[k];
      }
      return value || key;
    },
    [language] // Only language is a reactive dependency; k, keys are local variables
  );

  const contextValue = useMemo(
    () => ({ language, setLanguage, toggleLanguage, t }),
    [language, toggleLanguage, t]
  );

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
